#!/bin/sh

set -e

v -g -enable-globals crun . -elf $@ > a.o.fasm
fasm a.o.fasm a.o -m 1048576
ld a.o -o a.out
gdb ./a.out \
	-ex 'set debuginfod enabled off' \
	-ex 'lay asm' \
	-ex 'b main' \
	-ex 'run'